name: Dependency Security Check and Auto-Update

on:
  schedule:
    - cron: '0 2 * * 1' # Weekly on Monday at 2 AM
  workflow_dispatch:
  pull_request:
    paths:
      - 'package.json'
      - 'package-lock.json'

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.2'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: |
          npm audit --audit-level=high --production
          npm audit fix --dry-run > audit-report.txt

      - name: Check for vulnerabilities
        id: vuln-check
        run: |
          if npm audit --audit-level=high --production; then
            echo "vulnerabilities=false" >> $GITHUB_OUTPUT
          else
            echo "vulnerabilities=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Issue for Vulnerabilities
        if: steps.vuln-check.outputs.vulnerabilities == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const auditReport = fs.readFileSync('audit-report.txt', 'utf8');
            
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Security Vulnerabilities Detected',
              body: `Security vulnerabilities have been detected in dependencies:\n\n\`\`\`\n${auditReport}\n\`\`\`\n\nPlease review and update affected packages.`,
              labels: ['security', 'dependencies']
            });

#  auto-merge-dependabot:
#    runs-on: ubuntu-latest
#    if: ${{ github.actor == 'dependabot[bot]' }}
#    steps:
#      - name: Dependabot metadata
#        id: metadata
#        uses: dependabot/fetch-metadata@v2
#        with:
#          github-token: "${{ secrets.GITHUB_TOKEN }}"
#
#      - name: Auto-merge patch updates
#        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
#        run: gh pr merge --auto --merge "$PR_URL"
#        env:
#          PR_URL: ${{github.event.pull_request.html_url}}
#          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}